version: "3.7"

networks:
    po_webnet:
        external: true

services:
    impact:
        build:
            context: .
            dockerfile: Dockerfile
        restart: no
        networks:
            - po_webnet
        volumes:
            - ".:/app"
        command:
            [
                "python",
                "main.py",
                "--productopener_base_url",
                "http://frontend/",
                "--productopener_host_header",
                "world.productopener.localhost",
                "--productopener_username",
                "ecoscore-impact-estimator",
                "--productopener_password",
                "estimator",
            ]
