version: "3.7"
services:
  impact:
    image: ghcr.io/openfoodfacts/impactestimator/estimator:$TAG
    restart: always
    environment:
      - PRODUCT_OPENER_URL
      - PRODUCT_OPENER_USERNAME
      - PRODUCT_OPENER_PASSWORD
      - PRODUCT_OPENER_BASIC_AUTH_PASSWORD
      - PRODUCT_OPENER_BASIC_AUTH_USERNAME
      - PRODUCT_OPENER_HOST_HEADER
      - MONITORING_PORT
      - DOCKER_CPUS
    deploy:
        resources:
            limits:
                cpus: ${DOCKER_CPUS}
    ports:
      - "${MONITORING_PORT}:${MONITORING_PORT}"
