# we use compose specification
# see https://github.com/compose-spec/compose-spec/blob/master/spec.md

services:
  explorer:
    restart: always
    image: ghcr.io/openfoodfacts/impactestimator/explorer:$TAG
    ports:
      - ${EXPOSE:-127.0.0.1:8080}:8080
    volumes:
      - ./binary:/go/src/explorer/binary
