name: Docker Image Build CI

on:
    push:
        branches:
            - main
            - deploy-*
            - release-v*.*.*
        tags:
            - v*.*.*

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # impact estimator
                name: 
                - estimator
                path: 
                - "."
                include:
                # explorer
                - name: explorer
                  path: "explorer/"
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
              with:
                  version: v0.6.0
                  buildkitd-flags: --debug

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: |
                      ghcr.io/${{ github.repository }}/${{ matrix.name }}
                  tags: |
                      type=semver,pattern={{version}}
                      type=ref,event=pr
                      type=ref,event=branch
                      type=sha,format=long
            # TODO: we currently IMPACT_LIB_REF to its default value which is refs/heads/master
            # we should normally fix a version
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: ${{ matrix.path }}
                  push: true
                  file: ${{ matrix.path }}/Dockerfile
                  cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.name }}:buildcache
                  cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.name }}:buildcache,mode=max
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
