name: Docker Image Build CI

on:
    push:
        branches:
            - main
            - deploy-*
            - release-v*.*.*
        tags:
            - v*.*.*

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # Note: versions are deployed to prod, while branches are deployed to preprod
                # hence the use of startsWith(github.ref, 'refs/tags/v')
                compose_project_name:
                - ${{ startsWith(github.ref, 'refs/tags/v') && 'ie_org' || 'ie_net' }}
                docker_cpus:
                - ${{ startsWith(github.ref, 'refs/tags/v') && '2.0' || '0.25' }}
                env:
                - ${{ startsWith(github.ref, 'refs/tags/v') && "" || "" }}
                include:
                # impact estimator
                - name: estimator
                  path: "."
                # explorer
                - name: explorer
                  path: "explorer/"
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
              with:
                  version: v0.6.0
                  buildkitd-flags: --debug

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: |
                      ghcr.io/${{ github.repository }}/${{ matrix.name }}
                  tags: |
                      type=semver,pattern={{version}}
                      type=ref,event=pr
                      type=ref,event=branch
                      type=sha,format=long
            # TODO: we currently IMPACT_LIB_REF to its default value which is refs/heads/master
            # we should normally fix a version
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ${{ matrix.path }}
                  push: true
                  file: Dockerfile
                  cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.name }}:buildcache
                  cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/${{ matrix.name }}:buildcache,mode=max
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
